//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleWebSite_Test.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleWebSite_Test.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;&lt;head&gt;
        ///&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=GB2312&quot;&gt;
        ///&lt;title&gt;GRE词汇表&lt;/title&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body&gt;
        ///
        ///
        ///&lt;p&gt;&lt;a target=&quot;_blank&quot; href=&quot;http://3g.dict.cn/s.php?q=abase&quot;&gt;abase&lt;/a&gt;&lt;/p&gt;
        ///&lt;p&gt;&lt;a target=&quot;_blank&quot; href=&quot;http://3g.dict.cn/s.php?q=abate&quot;&gt;abate&lt;/a&gt;&lt;/p&gt;
        ///&lt;p&gt;&lt;a target=&quot;_blank&quot; href=&quot;http://3g.dict.cn/s.php?q=abattoir&quot;&gt;abattoir&lt;/a&gt;&lt;/p&gt;
        ///
        ///&lt;p&gt;&lt;a target=&quot;_blank&quot; href=&quot;http://3g.dict.cn/s.php?q=abdicate&quot;&gt;abdicate&lt;/a&gt;&lt;/p&gt;
        ///&lt;p&gt;&lt;a target=&quot;_blank&quot; href=&quot;http://3g.dict.cn/s.php?q=abdomen&quot;&gt;a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GRE {
            get {
                return ResourceManager.GetString("GRE", resourceCulture);
            }
        }
    }
}
